export const UserActionTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
};

export const CartActionTypes = {
  TOGGLE_CART_VISIBLE: "TOGGLE_CART_VISIBLE",
  ADD_CART_ITEM: "ADD_CART_ITEM",
  REMOVE_CART_ITEM: "REMOVE_CART_ITEM",
  CLEAR_CART_ITEM: "CLEAR_CART_ITEM",
};

export const ShopActionTypes = {
  UPDATE_COLLECTIONS: "UPDATE_COLLECTIONS",
};
